### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by NoOneReally2021** [modul8co/homebridge-hikvision-nvr#2]
Hello, what resolution is being used with this plugin? There is quite a bit of latency when viewing camera while none when using hik connect app, both used at home on wifi

Anyway to tweak this?

Also is there options for more alerts such as line crossing? Thanks

**Comment by L0rdLogan** [comment]
The person who made this doesn't reply it seems

I can't get mine to work

**Comment by modul8co** [comment]
I currently maintain the following plugin:
https://github.com/modul8co/hikvision-nvr-events

Can you try that one and raise the issue on there?
